### ISSUE TITLE
Changing questionnaires in repo

### ISSUE THREAD

**Issue by sboettcher** [RADAR-base/RADAR-REDCap-aRMT-Definitions#114]
Question: Can I change translations (specifically german) for some of the questionnaires directly in the repo with a PR, or would that get overwritten by some automatic process in the future, e.g. pulling from some redcap instance?

**Comment by mpgxvii** [comment]
Yes you can change the translations directly. We usually only pull from Redcap specific questionnaires that we want to update.

**Comment by yatharthranjan** [comment]
Yes, if these are existing questionnaires that are imported from redcap, then it will be better to make the change in redcap and that will automatically propagate to github once the script is run. If the questionnaire is created directly here in github, then it's fine to update here. Can you specify exactly which questionnaires are to be updated? Thanks

**Comment by sboettcher** [comment]
OK, I'll make a PR when I have all the changes and then you can see if I need to change anything in redcap. I am still working through them, so I don't have a complete list yet.
