### ISSUE TITLE
Whitespace in questionnaire answer codes

### ISSUE THREAD

**Issue by CallumSa** [RADAR-base/RADAR-REDCap-aRMT-Definitions#7]
Hey,
The answers in most questionnaires have whitespace before non-0 'code's. 

E.g.          
in phq-8 question 1
```
        "select_choices_or_calculations": [
            {
                "code": "0",
                "label": " Not at all "
            },
            {
                "code": " 1",
                "label": " Several days "
            },
            {
                "code": " 2",
                "label": " More than half the days "
            },
    .....
```

Also in "patient_determined_disease_step" there is a "\r" before each answer code. Is there any reason we can't remove that whitespace? The schemas appear to consider the answer values as integers, at least the whitespace doesn't carry over into the exported CSV files.

**Comment by afolarin** [comment]
cc/ @kerzmaximilian  is this the normal output of the REDcap data-dictionary processing? Is there any reason for the padding?

**Comment by afolarin** [comment]
For Reference this is introduced by REDCap, and is now cleaned up. 
cc/ @CallumSa
