### ISSUE TITLE
Check index.js pushing mulitple questionnaires

### ISSUE THREAD

**Issue by kerzmaximilian** [RADAR-base/RADAR-REDCap-aRMT-Definitions#8]

**Comment by afolarin** [comment]
seems to be missing Dutch and Italian too..
![image](https://user-images.githubusercontent.com/2489685/44355641-0da0c800-a4a5-11e8-85db-986d7294d7fe.png)

**Comment by yatharthranjan** [comment]
Fixed with #9 and #11

**Comment by afolarin** [comment]
ok -- index.js I think is working as expected, save some of the issues outlined here https://github.com/RADAR-base/RADAR-Questionnaire/issues/146
